### ISSUE TITLE
Reimagined World Menu in Ukraine !

### ISSUE THREAD

**Issue by PetroTornado** [lamaprogramer/ReimaginedMenus#10]
Hello everyone, I completely translated your mod into Ukrainian
[New Архив ZIP - WinRAR.zip](https://github.com/lamaprogramer/ReimaginedMenus/files/11757330/New.ZIP.-.WinRAR.zip)

**Comment by lamaprogramer** [comment]
Just got around to adding it, it is now in the latest release
