### ISSUE TITLE
Mod causes game to crash when using vanilla "Recreate World" option.

### ISSUE THREAD

**Issue by MCRusher** [lamaprogramer/ReimaginedMenus#13]
I tested this with just this mod installed using Quilt loader 1.19.2

When I create a world, exit to menu and then select recreate for that world, the game will crash after a few seconds.

[crash-2023-07-17_10.35.43-client.txt](https://github.com/lamaprogramer/ReimaginedMenus/files/12070677/crash-2023-07-17_10.35.43-client.txt)

For now I'll just copy the seed manually and avoid using that option, but I figured I should let you know.

Side note, thanks for making this mod, It looks a lot nicer than the vanilla menu, and when combined with bedrockify looks even better with the panorama backgrounds.

**Comment by lamaprogramer** [comment]
Ok, I finally got around to fixing some bugs, and now it should work in the latest version, it is out on modrinth, andcurseforge has to approve the file so it may take a sec
