### ISSUE TITLE
[SUGGESTION] Add the ability to define custom banners for custom world presets via resource packs.

### ISSUE THREAD

**Issue by vico93** [lamaprogramer/ReimaginedMenus#16]
Would be interesting if mods that add custom world presets could ship a banner image for the mod - like for example having a `assets\reimaginedmenus\textures\misc\<custom world preset name>.png` inside the mod's internal resource pack.

**Comment by lamaprogramer** [comment]
That's actually a really good idea, I'll definitely look into that.

**Comment by lamaprogramer** [comment]
Alright, it's added
