### ISSUE TITLE
[Localization] Czech language file doesn't working.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [lamaprogramer/ReimaginedMenus#21]
Hello!

I've noticed that [cs_cz](https://github.com/lamaprogramer/ReimaginedMenus/blob/master/src/main/resources/assets/reimaginedmenus/lang/cs_cz) missing `.json` file extension... and because of it, the language file will not work.

**Comment by lamaprogramer** [comment]
All fixed!
