### ISSUE TITLE
Request. Compatibility with mod "World Preview"

### ISSUE THREAD

**Issue by bons66** [lamaprogramer/ReimaginedMenus#22]
World Preview is a mod for visualizing Minecraft world seeds before they are generated.
[https://modrinth.com/mod/world-preview](url)

**Comment by lamaprogramer** [comment]
Unfortunately this will not be possible, the tab layout of that mod won't translate well to my tab layout.

**Comment by vico93** [comment]
I was just to create a duplicate request for that until i found this one buried among the closed ones.

@lamaprogramer why not add a separate item on this corner of the screen?
![image](https://github.com/user-attachments/assets/af0834ca-26c4-4ad2-a9fb-deff140f515e)

Or as a button between the seed text field and the Generate Structures toggle:
![image](https://github.com/user-attachments/assets/8d02756e-bcaa-4ac3-b0c2-edf606d10601)

Pingging @caeruleusDraconis to see if something would need to be done on his side to support ReimaginedMenus (maybe offer an alternate screen outside the tabbed one just for this mod)

**Comment by lamaprogramer** [comment]
I could easily do that, however, the problem isn't where to open the menu, it's the mod's layout. It doesn't translate well to my layout, I would have to somehow completely redesign their GUI. So unless, compatibility is added on their side, I can't really do anything with it. However, I wouldn't expect them to, the code for my mod isn't easily externally extendable. I may eventually change this if or when compatibility becomes a main focus for this project.

**Comment by mateus3c** [comment]
honestly, even if World Preview design doesn't match your mod it's better to be able to have both mods together even if their designs doesn't instead of having to choose between one of the two
