### ISSUE TITLE
Crash after installing the mod (incompatibility with mod "Cycle Title Screen Splash"?)

### ISSUE THREAD

**Issue by vico93** [lamaprogramer/ReimaginedMenus#23]
Hello!

Basically, i'm using [Cycle Title Screen Splash](https://modrinth.com/mod/cycle-title-screen-splash) on my modpack, and after Reimagined Menus updated to 1.20.4 i tried to put it alongside them, but when i try to boot the game i got [this crash](https://gist.github.com/vico93/1af10d493d0d24e272b68ca7e7987298) instead.

Removing the Reimagined Menus .jar from the mod folder allows the game to boot properly.

What could be the problem?

**Comment by lamaprogramer** [comment]
At the moment, I'm not really sure, with just **Cycle Title Screen Splash**, **Collective**, and **Fabric Api**, it seems to work fine, both mods are doing what they're supposed to, I'm gonna try and download every mod in your modpack so I can see if another mod is acting like a third-wheel and causing problems, that may take a sec though cause I gotta go through the crash log and download each one manually for my dev environment. I'll let you know if I find anything out.

**Comment by vico93** [comment]
> At the moment, I'm not really sure. With just **Cycle Title Screen Splash**, **Collective**, and **Fabric Api**, it seems to work fine, both mods are doing what they're supposed to, I'm gonna try and download every mod in your modpack so I can see if another mod is acting like a third-wheel and causing problems, that may take a sec though cause I gotta go through the crash log and download each one manually for my dev environment. I'll let you know if I find anything out.

if you have interest i can zip my profile folder and send it to you

**Comment by vico93** [comment]
[HERE](https://drive.google.com/file/d/14JDeGv4fEN-PIYD8NJEduNtv5M5Ve4BR/view?usp=sharing)

**Comment by vico93** [comment]
Let me know when you finish downloading the file

**Comment by lamaprogramer** [comment]
alright, its downloaded

**Comment by vico93** [comment]
I don't know what happened, but i tested again after redownloading the latest version of ReimaginedMenus to send to you (i had removed the .jar after the crash to test) and this time no crash happened 😶 

I really dont know what went wrong before. Perharps i downloaded a wrong version of the mod, or some other thing happened the first time i tried 🤷🏻

**Comment by lamaprogramer** [comment]
Yeh, I was wondering about that, cause even after downloading your instance, everything between the two mods still worked fine, might’ve just been a weird one-off type thing, thanks for letting me know anyways👍🏾 I assume the issue is resolved then?

**Comment by vico93** [comment]
> Yeh, I was wondering about that, cause even after downloading your instance, everything between the two mods still worked fine, might’ve just been a weird one-off type thing, thanks for letting me know anyways👍🏾 I assume the issue is resolved then?

yeah, i think its solved! Thanks for your assistence!
