### ISSUE TITLE
Compatibility issue with Difficulty Lock

### ISSUE THREAD

**Issue by vico93** [lamaprogramer/ReimaginedMenus#24]
Hi!

In 1.20.1, seems like trying to have both ReimaginedMenus and @Serilum's [Difficulty Lock](https://github.com/Serilum/Difficulty-Lock) ([MR](https://modrinth.com/mod/difficulty-lock)) installed makes the Difficulty button on the new world screen always inactive regardless of the settings used on Difficulty Lock.

When one try to type something on the Name field, the button briefly activates for a millisecond and resumes being inactive.

reimaginedmenus-2.0.0-1.20.2.jar and difficultylock-1.20.1-4.0.jar

**Comment by lamaprogramer** [comment]
This appears to be an issue with [Difficulty Lock](https://github.com/Serilum/Difficulty-Lock), as what you are describing still persists without my mod installed, please post an issue on their mod page.

**Comment by vico93** [comment]
Thanks for the clarification. Reporting to @Serilum now!
