### ISSUE TITLE
Compatibilty with Cloth Gamerules

### ISSUE THREAD

**Issue by vico93** [lamaprogramer/ReimaginedMenus#27]
Basically, [that mod](https://modrinth.com/mod/cloth-gamerules) switch the Gamerules button to open its menu instead of vanilla one, and i Reimagined Menus override that.

If you can detect whatever that mod is present and keep its behavior would be amazing to have.

**Comment by vico93** [comment]
any news? @lamaprogramer

**Comment by lamaprogramer** [comment]
Not at the moment, been busy with a bunch of other stuff, so I haven't gotten the chance, I'll take a look at it whenever I make my next update.

**Comment by lamaprogramer** [comment]
Should now be added in version 3.0.0.
