### ISSUE TITLE
Tweak background 

### ISSUE THREAD

**Issue by vico93** [lamaprogramer/ReimaginedMenus#28]
![image](https://github.com/lamaprogramer/ReimaginedMenus/assets/3485505/00fb30b3-6887-48ec-a8be-ae48c9818bcd)

Well, this is the first time i noticed this (since in previous versions or the dirt background was still up or i used a mod to restore it), seems like the new world menu "inherits" the middle-shadowed area of the select world screen, but its ugly on the layout reimagined world menu adds.

Can it be removed to the whole background have the same tint of the upper part?

**Comment by lamaprogramer** [comment]
Yeh, that shouldn't be too hard to do, I'll take a look at it at.

**Comment by lamaprogramer** [comment]
Should now be added in version 3.0.0.
