### ISSUE TITLE
Crash when clicking the "World icons" button.

### ISSUE THREAD

**Issue by Zeykehasnt** [lamaprogramer/ReimaginedMenus#31]
When you press this button - the game instantly closes.

https://pastebin.com/7JGYC74x

Mods:
  [✔] customworldicons-1.1.0-1.20.x
  [✔] fabric-api-0.92.2+1.20.1
  [✔] reimaginedmenus-3.1.0-1.20.2

https://github.com/user-attachments/assets/a2c1b7e9-d50b-43c3-9bf3-5df4813ea5e4

**Comment by williamk-jr** [comment]
Ah, you don't actually need the Custom World Icons mod, as the mod was created from a feature already in Reimagined World Menus. The crash is likely a conflict between the two mods.

**Comment by Zeykehasnt** [comment]
> Ah, you don't actually need the Custom World Icons mod, as the mod was created from a feature already in Reimagined World Menus. The crash is likely a conflict between the two mods.

I removed the mentioned mod, but that doesn't seem to carry any weight.

https://pastebin.com/yDJQSTKa

**Comment by williamk-jr** [comment]
Ah, I see the problem, I'll try to get to it as soon as I can.

**Comment by williamk-jr** [comment]
Should be fixed now
